# Generated by Django 2.1 on 2018-08-18 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousingAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.UUID('a23ccfef-7ba7-4527-ab5f-beb8eebdbe85'), editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Nouvelle annonce', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(choices=[('SN', 'Sénégal'), ('CM', 'Caméroun'), ('CI', "Côte d'Ivoire"), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('MA', 'Maroc'), ('KE', 'Kenya'), ('TN', 'Tunisie')], default='SN', max_length=2)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('surface_area', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('ad_type', models.CharField(blank=True, choices=[('Housing', 'Logement')], default='Housing', max_length=20)),
                ('housing_type', models.CharField(blank=True, choices=[('House', 'Maison'), ('Flat', 'Appartement')], default='Flat', max_length=20)),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'Vente'), ('rent', 'Location')], default='rent', max_length=20)),
            ],
            options={
                'ordering': ('published',),
            },
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.UUID('d995e8c1-d1ed-41c9-9f8a-41cb8e23cacc'), editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Nouvelle annonce', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(choices=[('SN', 'Sénégal'), ('CM', 'Caméroun'), ('CI', "Côte d'Ivoire"), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('MA', 'Maroc'), ('KE', 'Kenya'), ('TN', 'Tunisie')], default='SN', max_length=2)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('ad_type', models.CharField(blank=True, choices=[('Job', 'Emploi')], default='Job', max_length=20)),
                ('subjects', models.CharField(blank=True, max_length=250)),
                ('gross_salary', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Undefined', 'Non précisé')], default='Undefined', max_length=20)),
            ],
            options={
                'ordering': ('published',),
            },
        ),
        migrations.CreateModel(
            name='LandAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.UUID('ebff2096-ae1f-4f1e-9ae6-0e2ef1058562'), editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Nouvelle annonce', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(choices=[('SN', 'Sénégal'), ('CM', 'Caméroun'), ('CI', "Côte d'Ivoire"), ('NG', 'Nigéria'), ('GH', 'Ghana'), ('MA', 'Maroc'), ('KE', 'Kenya'), ('TN', 'Tunisie')], default='SN', max_length=2)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('surface_area', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Titré'), ('Not Approved', 'Non Titré')], default='Approved', max_length=20)),
                ('ad_type', models.CharField(choices=[('land', 'Terrain')], default='Land', max_length=20)),
                ('transaction_type', models.CharField(blank=True, choices=[('buy', 'Vente'), ('rent', 'Location')], default='rent', max_length=20)),
            ],
            options={
                'ordering': ('published',),
            },
        ),
    ]
