# Generated by Django 2.1 on 2018-08-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='Nouvelle annonce', max_length=250)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('image', models.CharField(blank=True, max_length=250)),
                ('country', models.CharField(choices=[('CI', "Côte d'Ivoire"), ('CM', 'Caméroun'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('MA', 'Maroc'), ('NG', 'Nigéria'), ('SN', 'Sénégal'), ('TN', 'Tunisie')], default='SN', max_length=2)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('ad_type', models.CharField(choices=[('Housing', 'Housing'), ('Job', 'Job'), ('Land', 'Land')], default='House', max_length=20)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='HousingAd',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.Annonce')),
                ('surface_area', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('rooms', models.IntegerField(blank=True)),
                ('housing_type', models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement')], default='Appartement', max_length=20)),
                ('transaction_type', models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='Location', max_length=20)),
            ],
            bases=('ads.annonce',),
        ),
        migrations.CreateModel(
            name='JobAd',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.Annonce')),
                ('subjects', models.CharField(blank=True, max_length=250)),
                ('gros_salary', models.IntegerField(blank=True)),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Non précisé', 'Non précisé')], default='Non précisé', max_length=20)),
            ],
            bases=('ads.annonce',),
        ),
        migrations.CreateModel(
            name='LandAd',
            fields=[
                ('annonce_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ads.Annonce')),
                ('surface_area', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Titré', 'Titré'), ('Non Titré', 'Non Titré')], default='Titré', max_length=20)),
                ('transaction_type', models.CharField(choices=[('Vente', 'Vente'), ('Location', 'Location')], default='Location', max_length=20)),
            ],
            bases=('ads.annonce',),
        ),
    ]
