# Generated by Django 2.1 on 2018-08-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobad',
            old_name='gros_salary',
            new_name='gross_salary',
        ),
    ]
