# Generated by Django 2.1 on 2018-08-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20180813_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingad',
            name='housing_type',
            field=models.CharField(choices=[('House', 'Maison'), ('Flat', 'Appartement')], default='Flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingad',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Vente'), ('rent', 'Location')], default='rent', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobad',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Undefined', 'Non précisé')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='landad',
            name='status',
            field=models.CharField(choices=[('Approved', 'Titré'), ('Not Approved', 'Non Titré')], default='Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='landad',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Vente'), ('rent', 'Location')], default='rent', max_length=20),
        ),
    ]
