# Generated by Django 2.1 on 2018-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20180813_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='ad_type',
            field=models.CharField(choices=[('Housing', 'Maison'), ('Job', 'Emploi'), ('Land', 'Terrain')], default='House', max_length=20),
        ),
    ]
